apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chiaretto-app
  namespace: chiaretto-argocd
spec:
  destination:
    namespace: chiaretto-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/lgchiaretto/chiaretto-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
